app/user/views/__init__.py
from .views import *

app/user/views/views.py
from dependency_injector.wiring import inject, Provide
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import login_required, current_user, login_user, logout_user

from werkzeug.exceptions import InternalServerError

from app import db
from app.containers import Container
from app.user.domain.login_form import LoginForm
from app.user.domain.register_form import RegisterForm
from app.user.domain.user import User
from app.order.domain.order_repository import OrderRepository
from app.order.query.dao.order_summary_dao import OrderSummaryDao

bp = Blueprint('user', __name__,
               template_folder='../templates', static_folder="../static", url_prefix='/user/')


@bp.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if request.method == 'POST':
        if not form.validate_on_submit():
            raise InternalServerError('Invalid form')
        user = User.query.filter_by(
            username=request.form['username'], password=request.form['password']
        ).first()
        if user is None:
            raise InternalServerError('Login failed')
        login_user(user)
        flash('You were logged in.')
        next = request.args.get('next')
        return redirect(next or url_for('home'))
    return render_template('user/login.html.j2')


@bp.route('/signup/', methods=['GET', 'POST'])
def signup():
    form = RegisterForm()
    if request.method == 'POST':
        if not form.validate_on_submit():
            raise InternalServerError('Invalid form')
        user = User(
            username=request.form['username'],
            password=request.form['password'],
        )
        user.is_admin = True
        db.session.add(user)
        db.session.commit()
        login_user(user)
        return redirect(url_for('home'))
    return render_template('user/signin.html.j2')


@bp.route('/logout/')
@login_required
def logout():
    logout_user()
    flash('You were logged out.')
    return render_template('user/logged-out.html.j2')


@bp.route('/my/')
@login_required
def my():
    return render_template('user/my.html.j2')


@bp.route('/orders/')
@login_required
@inject
def orders(order_summary_dao: OrderSummaryDao = Provide[Container.order_summary_dao]):
    _orders = order_summary_dao.select_by_orderer(current_user.id)
    return render_template('user/orders.html.j2', orders=_orders)


@bp.route('/orders/<int:order_id>/', methods=['GET', ])
@login_required
@inject
def order_detail(order_id: int, order_repository: OrderRepository = Provide[Container.order_repository]):
    order = order_repository.find_by_id(order_id)
    if not order:
        return render_template('user/no_order.html.j2')
    if order.orderer != current_user:
        return render_template('user/not_your_order.html.j2')
    return render_template('user/order_detail.html.j2', order=order)

app/user/templates/user/logged-out.html.j2
{% extends "base.html.j2" %} {% block content %}
<div class="alert alert-info" role="alert">
    로그아웃했습니다.
</div>
{% endblock %}

app/user/templates/user/login.html.j2
{% extends "base.html.j2" %} 

{% block title %} 로그인 {% endblock %}
{% block content %}
<form method="post" class="form-inline">
  <div class="form-group">
    <label for="username">아이디</label>
    <input type="text" class="form-control" id="username" name="username" />
  </div>
  <div class="form-group">
    <label for="password">암호</label>
    <input type="password" class="form-control" id="password" name="password" />
  </div>
  <button type="submit" class="btn btn-default">로그인</button>
</form>
{% endblock %}

app/user/templates/user/my.html.j2
{% extends "base.html.j2" %} {% block title %} 마이 페이지 {% endblock %} {% block
content %}
<h2>{{ current_user.username }} 님</h2>
<ul>
  <li><a href="{{ url_for('user.orders') }}">주문 목록 보기</a></li>
</ul>
{% endblock %}

app/user/templates/user/no_order.html.j2
{% extends "base.html.j2" %} 

{% block title %} 내 주문 {% endblock %} 

{% block content %}
<div class="alert alert-danger" role="alert">
    존재하지 않는 주문입니다.[NO]
</div>
{% endblock %}

app/user/templates/user/not_your_order.html.j2
{% extends "base.html.j2" %} 

{% block title %} 내 주문 {% endblock %} 

{% block content %}
<div class="alert alert-danger" role="alert">
    존재하지 않는 주문입니다.[NYO]
</div>
{% endblock %}

app/user/templates/user/order_detail.html.j2
{% extends "base.html.j2" %} 

{% block title %} 주문 상세: {{ order.id }} {% endblock %} 

{% block content %}
<h2>주문 상세</h2>
{% include 'common/order/order_detail_part.html.j2' %}
<div class="panel panel-default">
    <div class="panel-body">
        {% if order.is_not_yet_shipped() %}
            <button id="cancelBtn" class="btn btn-default">주문 취소하기</button>
            <button id="changeShippingBtn" class="btn btn-default">배송지 변경하기</button>
        {% endif %}
        <a class="btn btn-default" href="{{ url_for('user.orders') }}" role="button">주문 목록 보기</a>
        <a class="btn btn-default" href="{{ url_for('home') }}" role="button">첫 화면으로 이동하기</a>
    </div>
</div>

<form id="goCancelForm" action="{{ url_for('order.cancel', order_id=order.id) }}" method="post"></form>
<form id="goChangeShippingForm" action="{{ url_for('order.change_shipping_info', order_id=order.id) }}" method="get"></form>

<script>
    $(function () {
        $("#cancelBtn").click(function () {
            if (confirm("주문을 취소하시겠습니까?")) {
                $("#goCancelForm").submit();
            }
        });
        $("#changeShippingBtn").click(function () {
            $("#goChangeShippingForm").submit();
        });
    });
</script>
{% endblock %}

app/user/templates/user/orders.html.j2
{% extends "base.html.j2" %} 

{% block title %} 주문 목록 {% endblock %} 

{% block content %}
<h2>주문 목록</h2>
{% if orders|length %}
<table class="table">
  <thead>
    <tr>
      <th>주문번호</th>
      <th>금액</th>
      <th>상태</th>
      <th>상품</th>
    </tr>
  </thead>
  <tbody>
    {% for order in orders %}
    <tr>
      <td><a href="{{ url_for('user.order_detail', order_id=order.order_id) }}">
        {{order.order_id}}</a></td>
      <td>{{order.total_amounts}}</td>
      <td>{{order.state}}</td>
      <td>{{order.product_name}} 등</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<div class="alert alert-info" role="alert">주문 내역이 없습니다.</div>
{% endif %} 
{% endblock %}

app/user/templates/user/signin.html.j2
{% extends "base.html.j2" %} {% block content %}
<form method="post">
  <div class="form-group">
    <label for="username">Username</label>
    <input type="text" class="form-control" name="username" placeholder="username">
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input type="password" class="form-control" name="password" placeholder="password">
  </div>
  <div class="form-group form-check">
    <input type="checkbox" class="form-check-input" name="is_admin">
    <label class="form-check-label" for="is_admin">Admin</label>
  </div>
  <button type="submit" class="btn btn-primary">가입하기</button>
</form>
{% endblock %}