app/order/views/__init__.py
from .views import *

app/order/views/views.py
from dependency_injector.wiring import inject, Provide

from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import login_required, current_user

from app.containers import Container

from app.order.domain.shipping_info import ShippingInfo, Receiver, Address
from app.order.application.exceptions import NoOrderProductException
from app.order.application.place_order_service import PlaceOrderService
from app.order.application.cancel_order_service import CancelOrderService
from app.order.domain.order_repository import OrderRepository

bp = Blueprint('order', __name__,
               template_folder='../templates', static_folder="../static", url_prefix='/order/')


@ login_required
@ bp.route('/place/', methods=['POST', ])
@ inject
def place(place_order_service: PlaceOrderService = Provide[Container.place_order_service]):
    shipping_info = extract_shipping_info(request)
    order = place_order_service.place_order(current_user, shipping_info)
    return redirect(url_for('order.complete', order_id=order.id))


def extract_shipping_info(request):
    receiver_name = request.form.get('shipping_info.receiver.name')
    receiver_phone = request.form.get('shipping_info.receiver.phone')
    receiver = Receiver(name=receiver_name, phone=receiver_phone)
    zip_code = request.form.get('shipping_info.address.zip_code')
    address1 = request.form.get('shipping_info.address.address1')
    address2 = request.form.get('shipping_info.address.address2')
    address = Address(zip_code=zip_code, address1=address1, address2=address2)
    message = request.form.get('shipping_info.message')
    return ShippingInfo(receiver=receiver, address=address, message=message)


@ login_required
@ bp.route('/<int:order_id>/complete/', methods=['GET', ])
def complete(order_id: int):
    return render_template('order/order_complete.html.j2', order_id=order_id)


@ login_required
@ bp.route('/<int:order_id>/cancel/', methods=['POST', ])
@ inject
def cancel(order_id: int,
           cancel_order_service: CancelOrderService = Provide[Container.cancel_order_service]):
    cancel_order_service.cancel(order_id, current_user)
    return redirect(url_for('order.canceled', order_id=order_id))


@ login_required
@ bp.route('/<int:order_id>/canceled/', methods=['GET', ])
def canceled(order_id: int):
    return render_template('order/order_canceled.html.j2', order_id=order_id)


@ login_required
@ bp.route('/<int:order_id>/change_shipping_info/', methods=['GET', 'POST', ])
@ inject
def change_shipping_info(order_id: int,
                         order_repository: OrderRepository = Provide[Container.order_repository]):
    order = order_repository.find_by_id(order_id)
    if request.method == 'GET':
        return render_template('order/change_shipping_info.html.j2', order=order)
    if request.method == 'POST':
        order.shipping_info = extract_shipping_info(request)
        order_repository.save(order)
        return redirect(url_for('user.order_detail', order_id=order_id))


@ bp.app_errorhandler(NoOrderProductException)
def handle_no_order_product_exception(e):
    return 'There is no given product.', 400

app/order/templates/order/change_shipping_info.html.j2
{% extends "base.html.j2" %} 

{% block title %} 주문 정보 수정 {% endblock %}

{% block content %}
<div class="container">
    <form cssClass="form-horizontal" method="post" action="{{ url_for('order.change_shipping_info', order_id=order.id) }}">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">주문자</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                    <label class="col-sm-2 control-label">이름</label>
                    <div class="col-sm-10">
                        <p class="form-control-static">{{ order.orderer.username }}</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">받는 사람</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                    <label for="shipping_info.receiver.name" class="col-sm-2 control-label">이름
                        <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span></label>
                    <div class="col-sm-10">
                        <input name="shipping_info.receiver.name" cssClass="form-control" 
                            value="{{ order.shipping_info.receiver.name }}" />
                    </div>
                </div>
                <div class="form-group">
                    <label for="shipping_info.receiver.phone" class="col-sm-2 control-label">연락처
                        <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span></label>
                    <div class="col-sm-10">
                        <input name="shipping_info.receiver.phone" cssClass="form-control" 
                            value="{{ order.shipping_info.receiver.phone }}" />
                    </div>
                </div>
                <div class="form-group">
                    <label for="shipping_info.address.zip_code" class="col-sm-2 control-label">우편번호
                        <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span></label>
                    <div class="col-sm-10">
                        <input name="shipping_info.address.zip_code" cssClass="form-control"  
                            value="{{ order.shipping_info.address.zip_code }}" />
                    </div>
                </div>
                <div class="form-group">
                    <label for="shipping_info.address.address1" class="col-sm-2 control-label">주소1
                        <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span></label>
                    <div class="col-sm-10">
                        <input name="shipping_info.address.address1" cssClass="form-control" 
                            value="{{ order.shipping_info.address.address1 }}" />
                    </div>
                </div>
                <div class="form-group">
                    <label for="shipping_info.address.address2" class="col-sm-2 control-label">주소2
                        <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span></label>
                    <div class="col-sm-10">
                        <input name="shipping_info.address.address2" cssClass="form-control" 
                            value="{{ order.shipping_info.address.address2 }}" />
                    </div>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-body">
                <button type="submit" class="btn btn-primary">변경하기</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

app/order/templates/order/order_canceled.html.j2
{% extends "base.html.j2" %} 

{% block title %} 마이샵 {% endblock %}

{% block content %}
<div class="container">
    <div class="alert alert-success" role="alert">
        주문[{{ order_id }}]을 취소했습니다.
    </div>

    <a class="btn btn-primary" href="{{ url_for('user.order_detail', order_id=order_id) }}" role="button">주문 내역 보기</a>
    <a class="btn btn-default" href="{{ url_for('user.orders') }}", role="button">주문 목록 보기</a>
    <a class="btn btn-btn" href="{{url_for('home')}}" role="button">첫 화면으로 이동하기</a>
</div>
{% endblock %}

app/order/templates/order/order_complete.html.j2
{% extends "base.html.j2" %} 

{% block title %} 마이샵 {% endblock %}

{% block content %}
<div class="container">
    <div class="alert alert-success" role="alert">
        주문[{{order_id}}]을 완료했습니다.
    </div>

    <a class="btn btn-primary" href="{{ url_for('user.order_detail', order_id=order_id) }}" role="button">주문 내역 보기</a>
    <a class="btn btn-btn" href="{{url_for('home')}}" role="button">첫 화면으로 이동하기</a>
</div>
{% endblock %}