app/catalog/views/__init__.py
from .views import *

app/catalog/views/no_category_error.py
from werkzeug.exceptions import InternalServerError


class NoCategoryEx(InternalServerError):
    description = 'No category error'

    def __init__(self, response=None, original_exception=None):
        self.original_exception = original_exception
        super(InternalServerError, self).__init__(
            description=description, response=response
        )

app/catalog/views/views.py
from flask import Blueprint, render_template
from dependency_injector.wiring import inject, Provide

from app.containers import Container
from app.catalog.domain.category_repository import CategoryRepository
from app.catalog.domain.product_repository import ProductRepository
from app.catalog.application.product_service import ProductService
bp = Blueprint('catalog', __name__,
               template_folder='../templates', static_folder="../static", url_prefix='/catalog/')


@bp.route('/categories', methods=('GET',))
@inject
def categories(
        category_repository: CategoryRepository = Provide[Container.category_repository]):
    _categories = category_repository.find_all()
    return render_template('catalog/categories.html.j2', categories=_categories)


@bp.route('/categories/<int:category_id>/', methods=('GET',))
@inject
def category_products(category_id: int,
                      product_service: ProductService = Provide[Container.product_service]):
    category_product_page = product_service.find_products_in_category_id(
        category_id, 0, 10)
    return render_template('catalog/category_products.html.j2', category_product_page=category_product_page)


@bp.route('/products/<int:product_id>/', methods=('GET',))
@inject
def product_detail(product_id: int,
                   product_repository: ProductRepository = Provide[Container.product_repository]):
    product = product_repository.find_by_id(product_id)
    return render_template('catalog/product_detail.html.j2', product=product)

app/catalog/templates/catalog/categories.html.j2
{% extends "base.html.j2" %} 

{% block title %} 카테고리 목록 {% endblock %} 

{% block content %}
<h3>카테고리 목록</h3>
<ul>
  {% for category in categories %}
  <li><a href="{{ url_for('catalog.category_products', category_id=category.id) }}">
    {{category.name}}
  </a></li>
  {% endfor %}
</ul>
{% endblock %}

app/catalog/templates/catalog/category_products.html.j2
{% extends "base.html.j2" %} 

{% block title %} 제품 목록 {% endblock %} 

{% block content %}
<h2>{{ category_product_page.category.name }}</h2>
{% if category_product_page.products |length %}
  {% for product in category_product_page.products %}
    <div class="media">
      <div class="media-left">
        <a href="{{ url_for('catalog.product_detail', product_id=product.id) }}">
          <img class="media-object" style="width: 64px; height: 64px;" 
          src="{{ product.image_url }}" alt="{{ product.name }}">
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading">{{ product.name }}</h4>
        가격 : {{ product.price }}
      </div>
    </div>
  {% endfor %}
{% else %}
    <div class="alert alert-info" role="alert">
        제품이 없습니다.
    </div>
{% endif %}
{% endblock %}

app/catalog/templates/catalog/product_detail.html.j2
{% extends "base.html.j2" %} 

{% block title %} 제품 상세 {% endblock %} 

{% block content %}
<form method="post" action="{{ url_for('cart.add_cart') }}">
    <div class="row">
        <div class="col-md-4">
            <img src="{{ product.image_url }}" class="img-responsive">
        </div>
        <div class="col-md-8">
            <div class="panel panel-default">
                <div class="panel-heading">{{ product.name }}</div>
                <div class="panel-body">
                    가격 : {{ product.price }}
                    <br>
                    상세 : {{ product.detail }}
                </div>
            </div>
            <div>
                <input type="hidden" name="product_id" value="{{ product.id }}"/>
                <input type="hidden" name="quantity" value="1"/>
                <button type="submit" class="btn btn-primary btn-lg" id="orderBtn">구매하기</button>
            </div>
        </div>
    </div>
</form>
<script>
    $(function() {
        $("#orderBtn").click(function() {
            handleOrder();
        });
    });
    {% if current_user.is_authenticated %} 
    function handleOrder() {
        alert("주문 확인 화면으로 넘어갑니다.");
        $("#orderBtn").submit()
    }
    
    {% else %}
    function handleOrder() {
        alert("로그인을 먼저 하세요!");
    }
    {% endif %}
</script>
{% endblock %}